### store a user data in mongodb user collection

POST http://localhost:7777/signup
content-Type:application/json

{
  "firstName": "Padma",
  "lastName": "ajith",
  "emailId": "padma@gmail.com",
  "password": "padma23"
}