### store a user data in mongodb user collection

POST http://localhost:7777/signup
content-Type:application/json

{
  "firstName": "Dhoni",
  "emailId": " dni@gmail.com ",
  "password": "Dhoni3478",
  "gender":"male",
  "skills":["Cricket","Cool"]
  
}


### Get a specific user details

GET http://localhost:7777/profile
content-Type:application/json

{
  "emailId":"ajithkumar@gmail.com"
}

### Gell all user details
GET http://localhost:7777/feed


### Update a user profile
PATCH  http://localhost:7777/user/688dc10b9e1404ca943d26f3
content-Type:application/json

{
  "bio": "Wife of Virat."
}


### Delete a profile by emailId
DELETE http://localhost:7777/user
content-Type:application/json

{
  "id":"688dc33f8a54bfe14e77798e"
}

### delete all documents from a collection
DELETE http://localhost:7777/allusers
